/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfRouteImport } from './routes/prof'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EleveRouteImport } from './routes/eleve'
import { Route as ConnexionParentRouteImport } from './routes/connexion-parent'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfIndexRouteImport } from './routes/prof/index'
import { Route as ParentIndexRouteImport } from './routes/parent/index'
import { Route as EleveIndexRouteImport } from './routes/eleve/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfRapportsRouteImport } from './routes/prof/rapports'
import { Route as ProfPreferencesRouteImport } from './routes/prof/preferences'
import { Route as ProfPlanningRouteImport } from './routes/prof/planning'
import { Route as ProfNotificationsRouteImport } from './routes/prof/notifications'
import { Route as ProfMessagesRouteImport } from './routes/prof/messages'
import { Route as ParentPreferencesRouteImport } from './routes/parent/preferences'
import { Route as ParentNotificationsRouteImport } from './routes/parent/notifications'
import { Route as ParentDevoirsRouteImport } from './routes/parent/devoirs'
import { Route as ParentBoutiqueRouteImport } from './routes/parent/boutique'
import { Route as EleveProfilRouteImport } from './routes/eleve/profil'
import { Route as ElevePreferencesRouteImport } from './routes/eleve/preferences'
import { Route as EleveNotificationsRouteImport } from './routes/eleve/notifications'
import { Route as EleveMonAbonnementRouteImport } from './routes/eleve/mon-abonnement'
import { Route as EleveMessagesRouteImport } from './routes/eleve/messages'
import { Route as EleveLiveRouteImport } from './routes/eleve/live'
import { Route as EleveJeuRouteImport } from './routes/eleve/jeu'
import { Route as EleveHistoriqueRouteImport } from './routes/eleve/historique'
import { Route as EleveDashboardRouteImport } from './routes/eleve/dashboard'
import { Route as EleveCoachRouteImport } from './routes/eleve/coach'
import { Route as EleveClassementRouteImport } from './routes/eleve/classement'
import { Route as EleveBoutiqueRouteImport } from './routes/eleve/boutique'
import { Route as EleveBadgesRouteImport } from './routes/eleve/badges'
import { Route as EleveAbonnementRouteImport } from './routes/eleve/abonnement'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminRessourcesRouteImport } from './routes/admin/ressources'
import { Route as AdminPermissionsRouteImport } from './routes/admin/permissions'
import { Route as AdminParametresRouteImport } from './routes/admin/parametres'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMatieresRouteImport } from './routes/admin/matieres'
import { Route as AdminMarketplaceRouteImport } from './routes/admin/marketplace'
import { Route as AdminClassesRouteImport } from './routes/admin/classes'
import { Route as AdminAbonnementsRouteImport } from './routes/admin/abonnements'
import { Route as ProfRessourcesIndexRouteImport } from './routes/prof/ressources/index'
import { Route as ProfProduitsIndexRouteImport } from './routes/prof/produits/index'
import { Route as ProfGroupesIndexRouteImport } from './routes/prof/groupes/index'
import { Route as ProfExercicesIndexRouteImport } from './routes/prof/exercices/index'
import { Route as ProfElevesIndexRouteImport } from './routes/prof/eleves/index'
import { Route as EleveExamensIndexRouteImport } from './routes/eleve/examens/index'
import { Route as EleveDevoirsIndexRouteImport } from './routes/eleve/devoirs/index'
import { Route as EleveBibliothequeIndexRouteImport } from './routes/eleve/bibliotheque/index'
import { Route as AdminUtilisateursIndexRouteImport } from './routes/admin/utilisateurs/index'
import { Route as AdminQuestionsIndexRouteImport } from './routes/admin/questions/index'
import { Route as AdminGestionnairesIndexRouteImport } from './routes/admin/gestionnaires/index'
import { Route as AdminExamensIndexRouteImport } from './routes/admin/examens/index'
import { Route as ProfRessourcesIdRouteImport } from './routes/prof/ressources/$id'
import { Route as ProfProduitsIdRouteImport } from './routes/prof/produits/$id'
import { Route as ProfGroupesIdRouteImport } from './routes/prof/groupes/$id'
import { Route as ProfExercicesNouveauRouteImport } from './routes/prof/exercices/nouveau'
import { Route as ProfExercicesIdRouteImport } from './routes/prof/exercices/$id'
import { Route as ProfElevesIdRouteImport } from './routes/prof/eleves/$id'
import { Route as EleveSalleIdRouteImport } from './routes/eleve/salle/$id'
import { Route as EleveExamensIdRouteImport } from './routes/eleve/examens/$id'
import { Route as EleveDevoirsIdRouteImport } from './routes/eleve/devoirs/$id'
import { Route as EleveBibliothequeIdRouteImport } from './routes/eleve/bibliotheque/$id'
import { Route as AdminUtilisateursIdRouteImport } from './routes/admin/utilisateurs/$id'
import { Route as AdminQuestionsNouveauRouteImport } from './routes/admin/questions/nouveau'
import { Route as AdminQuestionsQuestionIdRouteImport } from './routes/admin/questions/$questionId'
import { Route as AdminGroupesIdRouteImport } from './routes/admin/groupes/$id'
import { Route as AdminGestionnairesIdRouteImport } from './routes/admin/gestionnaires/$id'
import { Route as AdminExamensExamIdRouteImport } from './routes/admin/examens/$examId'
import { Route as AdminDevoirsIdRouteImport } from './routes/admin/devoirs/$id'

const ProfRoute = ProfRouteImport.update({
  id: '/prof',
  path: '/prof',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EleveRoute = EleveRouteImport.update({
  id: '/eleve',
  path: '/eleve',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionParentRoute = ConnexionParentRouteImport.update({
  id: '/connexion-parent',
  path: '/connexion-parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfIndexRoute = ProfIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const EleveIndexRoute = EleveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EleveRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfRapportsRoute = ProfRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => ProfRoute,
} as any)
const ProfPreferencesRoute = ProfPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ProfRoute,
} as any)
const ProfPlanningRoute = ProfPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => ProfRoute,
} as any)
const ProfNotificationsRoute = ProfNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfRoute,
} as any)
const ProfMessagesRoute = ProfMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ProfRoute,
} as any)
const ParentPreferencesRoute = ParentPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ParentRoute,
} as any)
const ParentNotificationsRoute = ParentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ParentRoute,
} as any)
const ParentDevoirsRoute = ParentDevoirsRouteImport.update({
  id: '/devoirs',
  path: '/devoirs',
  getParentRoute: () => ParentRoute,
} as any)
const ParentBoutiqueRoute = ParentBoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => ParentRoute,
} as any)
const EleveProfilRoute = EleveProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => EleveRoute,
} as any)
const ElevePreferencesRoute = ElevePreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => EleveRoute,
} as any)
const EleveNotificationsRoute = EleveNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EleveRoute,
} as any)
const EleveMonAbonnementRoute = EleveMonAbonnementRouteImport.update({
  id: '/mon-abonnement',
  path: '/mon-abonnement',
  getParentRoute: () => EleveRoute,
} as any)
const EleveMessagesRoute = EleveMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => EleveRoute,
} as any)
const EleveLiveRoute = EleveLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => EleveRoute,
} as any)
const EleveJeuRoute = EleveJeuRouteImport.update({
  id: '/jeu',
  path: '/jeu',
  getParentRoute: () => EleveRoute,
} as any)
const EleveHistoriqueRoute = EleveHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => EleveRoute,
} as any)
const EleveDashboardRoute = EleveDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EleveRoute,
} as any)
const EleveCoachRoute = EleveCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => EleveRoute,
} as any)
const EleveClassementRoute = EleveClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => EleveRoute,
} as any)
const EleveBoutiqueRoute = EleveBoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => EleveRoute,
} as any)
const EleveBadgesRoute = EleveBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => EleveRoute,
} as any)
const EleveAbonnementRoute = EleveAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => EleveRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRessourcesRoute = AdminRessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatieresRoute = AdminMatieresRouteImport.update({
  id: '/matieres',
  path: '/matieres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplaceRoute = AdminMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbonnementsRoute = AdminAbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => AdminRoute,
} as any)
const ProfRessourcesIndexRoute = ProfRessourcesIndexRouteImport.update({
  id: '/ressources/',
  path: '/ressources/',
  getParentRoute: () => ProfRoute,
} as any)
const ProfProduitsIndexRoute = ProfProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => ProfRoute,
} as any)
const ProfGroupesIndexRoute = ProfGroupesIndexRouteImport.update({
  id: '/groupes/',
  path: '/groupes/',
  getParentRoute: () => ProfRoute,
} as any)
const ProfExercicesIndexRoute = ProfExercicesIndexRouteImport.update({
  id: '/exercices/',
  path: '/exercices/',
  getParentRoute: () => ProfRoute,
} as any)
const ProfElevesIndexRoute = ProfElevesIndexRouteImport.update({
  id: '/eleves/',
  path: '/eleves/',
  getParentRoute: () => ProfRoute,
} as any)
const EleveExamensIndexRoute = EleveExamensIndexRouteImport.update({
  id: '/examens/',
  path: '/examens/',
  getParentRoute: () => EleveRoute,
} as any)
const EleveDevoirsIndexRoute = EleveDevoirsIndexRouteImport.update({
  id: '/devoirs/',
  path: '/devoirs/',
  getParentRoute: () => EleveRoute,
} as any)
const EleveBibliothequeIndexRoute = EleveBibliothequeIndexRouteImport.update({
  id: '/bibliotheque/',
  path: '/bibliotheque/',
  getParentRoute: () => EleveRoute,
} as any)
const AdminUtilisateursIndexRoute = AdminUtilisateursIndexRouteImport.update({
  id: '/utilisateurs/',
  path: '/utilisateurs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsIndexRoute = AdminQuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGestionnairesIndexRoute = AdminGestionnairesIndexRouteImport.update({
  id: '/gestionnaires/',
  path: '/gestionnaires/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamensIndexRoute = AdminExamensIndexRouteImport.update({
  id: '/examens/',
  path: '/examens/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfRessourcesIdRoute = ProfRessourcesIdRouteImport.update({
  id: '/ressources/$id',
  path: '/ressources/$id',
  getParentRoute: () => ProfRoute,
} as any)
const ProfProduitsIdRoute = ProfProduitsIdRouteImport.update({
  id: '/produits/$id',
  path: '/produits/$id',
  getParentRoute: () => ProfRoute,
} as any)
const ProfGroupesIdRoute = ProfGroupesIdRouteImport.update({
  id: '/groupes/$id',
  path: '/groupes/$id',
  getParentRoute: () => ProfRoute,
} as any)
const ProfExercicesNouveauRoute = ProfExercicesNouveauRouteImport.update({
  id: '/exercices/nouveau',
  path: '/exercices/nouveau',
  getParentRoute: () => ProfRoute,
} as any)
const ProfExercicesIdRoute = ProfExercicesIdRouteImport.update({
  id: '/exercices/$id',
  path: '/exercices/$id',
  getParentRoute: () => ProfRoute,
} as any)
const ProfElevesIdRoute = ProfElevesIdRouteImport.update({
  id: '/eleves/$id',
  path: '/eleves/$id',
  getParentRoute: () => ProfRoute,
} as any)
const EleveSalleIdRoute = EleveSalleIdRouteImport.update({
  id: '/salle/$id',
  path: '/salle/$id',
  getParentRoute: () => EleveRoute,
} as any)
const EleveExamensIdRoute = EleveExamensIdRouteImport.update({
  id: '/examens/$id',
  path: '/examens/$id',
  getParentRoute: () => EleveRoute,
} as any)
const EleveDevoirsIdRoute = EleveDevoirsIdRouteImport.update({
  id: '/devoirs/$id',
  path: '/devoirs/$id',
  getParentRoute: () => EleveRoute,
} as any)
const EleveBibliothequeIdRoute = EleveBibliothequeIdRouteImport.update({
  id: '/bibliotheque/$id',
  path: '/bibliotheque/$id',
  getParentRoute: () => EleveRoute,
} as any)
const AdminUtilisateursIdRoute = AdminUtilisateursIdRouteImport.update({
  id: '/utilisateurs/$id',
  path: '/utilisateurs/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsNouveauRoute = AdminQuestionsNouveauRouteImport.update({
  id: '/questions/nouveau',
  path: '/questions/nouveau',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsQuestionIdRoute =
  AdminQuestionsQuestionIdRouteImport.update({
    id: '/questions/$questionId',
    path: '/questions/$questionId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminGroupesIdRoute = AdminGroupesIdRouteImport.update({
  id: '/groupes/$id',
  path: '/groupes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGestionnairesIdRoute = AdminGestionnairesIdRouteImport.update({
  id: '/gestionnaires/$id',
  path: '/gestionnaires/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamensExamIdRoute = AdminExamensExamIdRouteImport.update({
  id: '/examens/$examId',
  path: '/examens/$examId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevoirsIdRoute = AdminDevoirsIdRouteImport.update({
  id: '/devoirs/$id',
  path: '/devoirs/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion-parent': typeof ConnexionParentRoute
  '/eleve': typeof EleveRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRouteWithChildren
  '/prof': typeof ProfRouteWithChildren
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/matieres': typeof AdminMatieresRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/ressources': typeof AdminRessourcesRoute
  '/admin/support': typeof AdminSupportRoute
  '/eleve/abonnement': typeof EleveAbonnementRoute
  '/eleve/badges': typeof EleveBadgesRoute
  '/eleve/boutique': typeof EleveBoutiqueRoute
  '/eleve/classement': typeof EleveClassementRoute
  '/eleve/coach': typeof EleveCoachRoute
  '/eleve/dashboard': typeof EleveDashboardRoute
  '/eleve/historique': typeof EleveHistoriqueRoute
  '/eleve/jeu': typeof EleveJeuRoute
  '/eleve/live': typeof EleveLiveRoute
  '/eleve/messages': typeof EleveMessagesRoute
  '/eleve/mon-abonnement': typeof EleveMonAbonnementRoute
  '/eleve/notifications': typeof EleveNotificationsRoute
  '/eleve/preferences': typeof ElevePreferencesRoute
  '/eleve/profil': typeof EleveProfilRoute
  '/parent/boutique': typeof ParentBoutiqueRoute
  '/parent/devoirs': typeof ParentDevoirsRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/preferences': typeof ParentPreferencesRoute
  '/prof/messages': typeof ProfMessagesRoute
  '/prof/notifications': typeof ProfNotificationsRoute
  '/prof/planning': typeof ProfPlanningRoute
  '/prof/preferences': typeof ProfPreferencesRoute
  '/prof/rapports': typeof ProfRapportsRoute
  '/admin/': typeof AdminIndexRoute
  '/eleve/': typeof EleveIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/prof/': typeof ProfIndexRoute
  '/admin/devoirs/$id': typeof AdminDevoirsIdRoute
  '/admin/examens/$examId': typeof AdminExamensExamIdRoute
  '/admin/gestionnaires/$id': typeof AdminGestionnairesIdRoute
  '/admin/groupes/$id': typeof AdminGroupesIdRoute
  '/admin/questions/$questionId': typeof AdminQuestionsQuestionIdRoute
  '/admin/questions/nouveau': typeof AdminQuestionsNouveauRoute
  '/admin/utilisateurs/$id': typeof AdminUtilisateursIdRoute
  '/eleve/bibliotheque/$id': typeof EleveBibliothequeIdRoute
  '/eleve/devoirs/$id': typeof EleveDevoirsIdRoute
  '/eleve/examens/$id': typeof EleveExamensIdRoute
  '/eleve/salle/$id': typeof EleveSalleIdRoute
  '/prof/eleves/$id': typeof ProfElevesIdRoute
  '/prof/exercices/$id': typeof ProfExercicesIdRoute
  '/prof/exercices/nouveau': typeof ProfExercicesNouveauRoute
  '/prof/groupes/$id': typeof ProfGroupesIdRoute
  '/prof/produits/$id': typeof ProfProduitsIdRoute
  '/prof/ressources/$id': typeof ProfRessourcesIdRoute
  '/admin/examens/': typeof AdminExamensIndexRoute
  '/admin/gestionnaires/': typeof AdminGestionnairesIndexRoute
  '/admin/questions/': typeof AdminQuestionsIndexRoute
  '/admin/utilisateurs/': typeof AdminUtilisateursIndexRoute
  '/eleve/bibliotheque/': typeof EleveBibliothequeIndexRoute
  '/eleve/devoirs/': typeof EleveDevoirsIndexRoute
  '/eleve/examens/': typeof EleveExamensIndexRoute
  '/prof/eleves/': typeof ProfElevesIndexRoute
  '/prof/exercices/': typeof ProfExercicesIndexRoute
  '/prof/groupes/': typeof ProfGroupesIndexRoute
  '/prof/produits/': typeof ProfProduitsIndexRoute
  '/prof/ressources/': typeof ProfRessourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion-parent': typeof ConnexionParentRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/matieres': typeof AdminMatieresRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/ressources': typeof AdminRessourcesRoute
  '/admin/support': typeof AdminSupportRoute
  '/eleve/abonnement': typeof EleveAbonnementRoute
  '/eleve/badges': typeof EleveBadgesRoute
  '/eleve/boutique': typeof EleveBoutiqueRoute
  '/eleve/classement': typeof EleveClassementRoute
  '/eleve/coach': typeof EleveCoachRoute
  '/eleve/dashboard': typeof EleveDashboardRoute
  '/eleve/historique': typeof EleveHistoriqueRoute
  '/eleve/jeu': typeof EleveJeuRoute
  '/eleve/live': typeof EleveLiveRoute
  '/eleve/messages': typeof EleveMessagesRoute
  '/eleve/mon-abonnement': typeof EleveMonAbonnementRoute
  '/eleve/notifications': typeof EleveNotificationsRoute
  '/eleve/preferences': typeof ElevePreferencesRoute
  '/eleve/profil': typeof EleveProfilRoute
  '/parent/boutique': typeof ParentBoutiqueRoute
  '/parent/devoirs': typeof ParentDevoirsRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/preferences': typeof ParentPreferencesRoute
  '/prof/messages': typeof ProfMessagesRoute
  '/prof/notifications': typeof ProfNotificationsRoute
  '/prof/planning': typeof ProfPlanningRoute
  '/prof/preferences': typeof ProfPreferencesRoute
  '/prof/rapports': typeof ProfRapportsRoute
  '/admin': typeof AdminIndexRoute
  '/eleve': typeof EleveIndexRoute
  '/parent': typeof ParentIndexRoute
  '/prof': typeof ProfIndexRoute
  '/admin/devoirs/$id': typeof AdminDevoirsIdRoute
  '/admin/examens/$examId': typeof AdminExamensExamIdRoute
  '/admin/gestionnaires/$id': typeof AdminGestionnairesIdRoute
  '/admin/groupes/$id': typeof AdminGroupesIdRoute
  '/admin/questions/$questionId': typeof AdminQuestionsQuestionIdRoute
  '/admin/questions/nouveau': typeof AdminQuestionsNouveauRoute
  '/admin/utilisateurs/$id': typeof AdminUtilisateursIdRoute
  '/eleve/bibliotheque/$id': typeof EleveBibliothequeIdRoute
  '/eleve/devoirs/$id': typeof EleveDevoirsIdRoute
  '/eleve/examens/$id': typeof EleveExamensIdRoute
  '/eleve/salle/$id': typeof EleveSalleIdRoute
  '/prof/eleves/$id': typeof ProfElevesIdRoute
  '/prof/exercices/$id': typeof ProfExercicesIdRoute
  '/prof/exercices/nouveau': typeof ProfExercicesNouveauRoute
  '/prof/groupes/$id': typeof ProfGroupesIdRoute
  '/prof/produits/$id': typeof ProfProduitsIdRoute
  '/prof/ressources/$id': typeof ProfRessourcesIdRoute
  '/admin/examens': typeof AdminExamensIndexRoute
  '/admin/gestionnaires': typeof AdminGestionnairesIndexRoute
  '/admin/questions': typeof AdminQuestionsIndexRoute
  '/admin/utilisateurs': typeof AdminUtilisateursIndexRoute
  '/eleve/bibliotheque': typeof EleveBibliothequeIndexRoute
  '/eleve/devoirs': typeof EleveDevoirsIndexRoute
  '/eleve/examens': typeof EleveExamensIndexRoute
  '/prof/eleves': typeof ProfElevesIndexRoute
  '/prof/exercices': typeof ProfExercicesIndexRoute
  '/prof/groupes': typeof ProfGroupesIndexRoute
  '/prof/produits': typeof ProfProduitsIndexRoute
  '/prof/ressources': typeof ProfRessourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion-parent': typeof ConnexionParentRoute
  '/eleve': typeof EleveRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRouteWithChildren
  '/prof': typeof ProfRouteWithChildren
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/matieres': typeof AdminMatieresRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/ressources': typeof AdminRessourcesRoute
  '/admin/support': typeof AdminSupportRoute
  '/eleve/abonnement': typeof EleveAbonnementRoute
  '/eleve/badges': typeof EleveBadgesRoute
  '/eleve/boutique': typeof EleveBoutiqueRoute
  '/eleve/classement': typeof EleveClassementRoute
  '/eleve/coach': typeof EleveCoachRoute
  '/eleve/dashboard': typeof EleveDashboardRoute
  '/eleve/historique': typeof EleveHistoriqueRoute
  '/eleve/jeu': typeof EleveJeuRoute
  '/eleve/live': typeof EleveLiveRoute
  '/eleve/messages': typeof EleveMessagesRoute
  '/eleve/mon-abonnement': typeof EleveMonAbonnementRoute
  '/eleve/notifications': typeof EleveNotificationsRoute
  '/eleve/preferences': typeof ElevePreferencesRoute
  '/eleve/profil': typeof EleveProfilRoute
  '/parent/boutique': typeof ParentBoutiqueRoute
  '/parent/devoirs': typeof ParentDevoirsRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/preferences': typeof ParentPreferencesRoute
  '/prof/messages': typeof ProfMessagesRoute
  '/prof/notifications': typeof ProfNotificationsRoute
  '/prof/planning': typeof ProfPlanningRoute
  '/prof/preferences': typeof ProfPreferencesRoute
  '/prof/rapports': typeof ProfRapportsRoute
  '/admin/': typeof AdminIndexRoute
  '/eleve/': typeof EleveIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/prof/': typeof ProfIndexRoute
  '/admin/devoirs/$id': typeof AdminDevoirsIdRoute
  '/admin/examens/$examId': typeof AdminExamensExamIdRoute
  '/admin/gestionnaires/$id': typeof AdminGestionnairesIdRoute
  '/admin/groupes/$id': typeof AdminGroupesIdRoute
  '/admin/questions/$questionId': typeof AdminQuestionsQuestionIdRoute
  '/admin/questions/nouveau': typeof AdminQuestionsNouveauRoute
  '/admin/utilisateurs/$id': typeof AdminUtilisateursIdRoute
  '/eleve/bibliotheque/$id': typeof EleveBibliothequeIdRoute
  '/eleve/devoirs/$id': typeof EleveDevoirsIdRoute
  '/eleve/examens/$id': typeof EleveExamensIdRoute
  '/eleve/salle/$id': typeof EleveSalleIdRoute
  '/prof/eleves/$id': typeof ProfElevesIdRoute
  '/prof/exercices/$id': typeof ProfExercicesIdRoute
  '/prof/exercices/nouveau': typeof ProfExercicesNouveauRoute
  '/prof/groupes/$id': typeof ProfGroupesIdRoute
  '/prof/produits/$id': typeof ProfProduitsIdRoute
  '/prof/ressources/$id': typeof ProfRessourcesIdRoute
  '/admin/examens/': typeof AdminExamensIndexRoute
  '/admin/gestionnaires/': typeof AdminGestionnairesIndexRoute
  '/admin/questions/': typeof AdminQuestionsIndexRoute
  '/admin/utilisateurs/': typeof AdminUtilisateursIndexRoute
  '/eleve/bibliotheque/': typeof EleveBibliothequeIndexRoute
  '/eleve/devoirs/': typeof EleveDevoirsIndexRoute
  '/eleve/examens/': typeof EleveExamensIndexRoute
  '/prof/eleves/': typeof ProfElevesIndexRoute
  '/prof/exercices/': typeof ProfExercicesIndexRoute
  '/prof/groupes/': typeof ProfGroupesIndexRoute
  '/prof/produits/': typeof ProfProduitsIndexRoute
  '/prof/ressources/': typeof ProfRessourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cgu'
    | '/confidentialite'
    | '/connexion-parent'
    | '/eleve'
    | '/onboarding'
    | '/parent'
    | '/prof'
    | '/admin/abonnements'
    | '/admin/classes'
    | '/admin/marketplace'
    | '/admin/matieres'
    | '/admin/notifications'
    | '/admin/parametres'
    | '/admin/permissions'
    | '/admin/ressources'
    | '/admin/support'
    | '/eleve/abonnement'
    | '/eleve/badges'
    | '/eleve/boutique'
    | '/eleve/classement'
    | '/eleve/coach'
    | '/eleve/dashboard'
    | '/eleve/historique'
    | '/eleve/jeu'
    | '/eleve/live'
    | '/eleve/messages'
    | '/eleve/mon-abonnement'
    | '/eleve/notifications'
    | '/eleve/preferences'
    | '/eleve/profil'
    | '/parent/boutique'
    | '/parent/devoirs'
    | '/parent/notifications'
    | '/parent/preferences'
    | '/prof/messages'
    | '/prof/notifications'
    | '/prof/planning'
    | '/prof/preferences'
    | '/prof/rapports'
    | '/admin/'
    | '/eleve/'
    | '/parent/'
    | '/prof/'
    | '/admin/devoirs/$id'
    | '/admin/examens/$examId'
    | '/admin/gestionnaires/$id'
    | '/admin/groupes/$id'
    | '/admin/questions/$questionId'
    | '/admin/questions/nouveau'
    | '/admin/utilisateurs/$id'
    | '/eleve/bibliotheque/$id'
    | '/eleve/devoirs/$id'
    | '/eleve/examens/$id'
    | '/eleve/salle/$id'
    | '/prof/eleves/$id'
    | '/prof/exercices/$id'
    | '/prof/exercices/nouveau'
    | '/prof/groupes/$id'
    | '/prof/produits/$id'
    | '/prof/ressources/$id'
    | '/admin/examens/'
    | '/admin/gestionnaires/'
    | '/admin/questions/'
    | '/admin/utilisateurs/'
    | '/eleve/bibliotheque/'
    | '/eleve/devoirs/'
    | '/eleve/examens/'
    | '/prof/eleves/'
    | '/prof/exercices/'
    | '/prof/groupes/'
    | '/prof/produits/'
    | '/prof/ressources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgu'
    | '/confidentialite'
    | '/connexion-parent'
    | '/onboarding'
    | '/admin/abonnements'
    | '/admin/classes'
    | '/admin/marketplace'
    | '/admin/matieres'
    | '/admin/notifications'
    | '/admin/parametres'
    | '/admin/permissions'
    | '/admin/ressources'
    | '/admin/support'
    | '/eleve/abonnement'
    | '/eleve/badges'
    | '/eleve/boutique'
    | '/eleve/classement'
    | '/eleve/coach'
    | '/eleve/dashboard'
    | '/eleve/historique'
    | '/eleve/jeu'
    | '/eleve/live'
    | '/eleve/messages'
    | '/eleve/mon-abonnement'
    | '/eleve/notifications'
    | '/eleve/preferences'
    | '/eleve/profil'
    | '/parent/boutique'
    | '/parent/devoirs'
    | '/parent/notifications'
    | '/parent/preferences'
    | '/prof/messages'
    | '/prof/notifications'
    | '/prof/planning'
    | '/prof/preferences'
    | '/prof/rapports'
    | '/admin'
    | '/eleve'
    | '/parent'
    | '/prof'
    | '/admin/devoirs/$id'
    | '/admin/examens/$examId'
    | '/admin/gestionnaires/$id'
    | '/admin/groupes/$id'
    | '/admin/questions/$questionId'
    | '/admin/questions/nouveau'
    | '/admin/utilisateurs/$id'
    | '/eleve/bibliotheque/$id'
    | '/eleve/devoirs/$id'
    | '/eleve/examens/$id'
    | '/eleve/salle/$id'
    | '/prof/eleves/$id'
    | '/prof/exercices/$id'
    | '/prof/exercices/nouveau'
    | '/prof/groupes/$id'
    | '/prof/produits/$id'
    | '/prof/ressources/$id'
    | '/admin/examens'
    | '/admin/gestionnaires'
    | '/admin/questions'
    | '/admin/utilisateurs'
    | '/eleve/bibliotheque'
    | '/eleve/devoirs'
    | '/eleve/examens'
    | '/prof/eleves'
    | '/prof/exercices'
    | '/prof/groupes'
    | '/prof/produits'
    | '/prof/ressources'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cgu'
    | '/confidentialite'
    | '/connexion-parent'
    | '/eleve'
    | '/onboarding'
    | '/parent'
    | '/prof'
    | '/admin/abonnements'
    | '/admin/classes'
    | '/admin/marketplace'
    | '/admin/matieres'
    | '/admin/notifications'
    | '/admin/parametres'
    | '/admin/permissions'
    | '/admin/ressources'
    | '/admin/support'
    | '/eleve/abonnement'
    | '/eleve/badges'
    | '/eleve/boutique'
    | '/eleve/classement'
    | '/eleve/coach'
    | '/eleve/dashboard'
    | '/eleve/historique'
    | '/eleve/jeu'
    | '/eleve/live'
    | '/eleve/messages'
    | '/eleve/mon-abonnement'
    | '/eleve/notifications'
    | '/eleve/preferences'
    | '/eleve/profil'
    | '/parent/boutique'
    | '/parent/devoirs'
    | '/parent/notifications'
    | '/parent/preferences'
    | '/prof/messages'
    | '/prof/notifications'
    | '/prof/planning'
    | '/prof/preferences'
    | '/prof/rapports'
    | '/admin/'
    | '/eleve/'
    | '/parent/'
    | '/prof/'
    | '/admin/devoirs/$id'
    | '/admin/examens/$examId'
    | '/admin/gestionnaires/$id'
    | '/admin/groupes/$id'
    | '/admin/questions/$questionId'
    | '/admin/questions/nouveau'
    | '/admin/utilisateurs/$id'
    | '/eleve/bibliotheque/$id'
    | '/eleve/devoirs/$id'
    | '/eleve/examens/$id'
    | '/eleve/salle/$id'
    | '/prof/eleves/$id'
    | '/prof/exercices/$id'
    | '/prof/exercices/nouveau'
    | '/prof/groupes/$id'
    | '/prof/produits/$id'
    | '/prof/ressources/$id'
    | '/admin/examens/'
    | '/admin/gestionnaires/'
    | '/admin/questions/'
    | '/admin/utilisateurs/'
    | '/eleve/bibliotheque/'
    | '/eleve/devoirs/'
    | '/eleve/examens/'
    | '/prof/eleves/'
    | '/prof/exercices/'
    | '/prof/groupes/'
    | '/prof/produits/'
    | '/prof/ressources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionParentRoute: typeof ConnexionParentRoute
  EleveRoute: typeof EleveRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ParentRoute: typeof ParentRouteWithChildren
  ProfRoute: typeof ProfRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prof': {
      id: '/prof'
      path: '/prof'
      fullPath: '/prof'
      preLoaderRoute: typeof ProfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleve': {
      id: '/eleve'
      path: '/eleve'
      fullPath: '/eleve'
      preLoaderRoute: typeof EleveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion-parent': {
      id: '/connexion-parent'
      path: '/connexion-parent'
      fullPath: '/connexion-parent'
      preLoaderRoute: typeof ConnexionParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prof/': {
      id: '/prof/'
      path: '/'
      fullPath: '/prof/'
      preLoaderRoute: typeof ProfIndexRouteImport
      parentRoute: typeof ProfRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/eleve/': {
      id: '/eleve/'
      path: '/'
      fullPath: '/eleve/'
      preLoaderRoute: typeof EleveIndexRouteImport
      parentRoute: typeof EleveRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/prof/rapports': {
      id: '/prof/rapports'
      path: '/rapports'
      fullPath: '/prof/rapports'
      preLoaderRoute: typeof ProfRapportsRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/preferences': {
      id: '/prof/preferences'
      path: '/preferences'
      fullPath: '/prof/preferences'
      preLoaderRoute: typeof ProfPreferencesRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/planning': {
      id: '/prof/planning'
      path: '/planning'
      fullPath: '/prof/planning'
      preLoaderRoute: typeof ProfPlanningRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/notifications': {
      id: '/prof/notifications'
      path: '/notifications'
      fullPath: '/prof/notifications'
      preLoaderRoute: typeof ProfNotificationsRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/messages': {
      id: '/prof/messages'
      path: '/messages'
      fullPath: '/prof/messages'
      preLoaderRoute: typeof ProfMessagesRouteImport
      parentRoute: typeof ProfRoute
    }
    '/parent/preferences': {
      id: '/parent/preferences'
      path: '/preferences'
      fullPath: '/parent/preferences'
      preLoaderRoute: typeof ParentPreferencesRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/notifications': {
      id: '/parent/notifications'
      path: '/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof ParentNotificationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/devoirs': {
      id: '/parent/devoirs'
      path: '/devoirs'
      fullPath: '/parent/devoirs'
      preLoaderRoute: typeof ParentDevoirsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/boutique': {
      id: '/parent/boutique'
      path: '/boutique'
      fullPath: '/parent/boutique'
      preLoaderRoute: typeof ParentBoutiqueRouteImport
      parentRoute: typeof ParentRoute
    }
    '/eleve/profil': {
      id: '/eleve/profil'
      path: '/profil'
      fullPath: '/eleve/profil'
      preLoaderRoute: typeof EleveProfilRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/preferences': {
      id: '/eleve/preferences'
      path: '/preferences'
      fullPath: '/eleve/preferences'
      preLoaderRoute: typeof ElevePreferencesRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/notifications': {
      id: '/eleve/notifications'
      path: '/notifications'
      fullPath: '/eleve/notifications'
      preLoaderRoute: typeof EleveNotificationsRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/mon-abonnement': {
      id: '/eleve/mon-abonnement'
      path: '/mon-abonnement'
      fullPath: '/eleve/mon-abonnement'
      preLoaderRoute: typeof EleveMonAbonnementRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/messages': {
      id: '/eleve/messages'
      path: '/messages'
      fullPath: '/eleve/messages'
      preLoaderRoute: typeof EleveMessagesRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/live': {
      id: '/eleve/live'
      path: '/live'
      fullPath: '/eleve/live'
      preLoaderRoute: typeof EleveLiveRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/jeu': {
      id: '/eleve/jeu'
      path: '/jeu'
      fullPath: '/eleve/jeu'
      preLoaderRoute: typeof EleveJeuRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/historique': {
      id: '/eleve/historique'
      path: '/historique'
      fullPath: '/eleve/historique'
      preLoaderRoute: typeof EleveHistoriqueRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/dashboard': {
      id: '/eleve/dashboard'
      path: '/dashboard'
      fullPath: '/eleve/dashboard'
      preLoaderRoute: typeof EleveDashboardRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/coach': {
      id: '/eleve/coach'
      path: '/coach'
      fullPath: '/eleve/coach'
      preLoaderRoute: typeof EleveCoachRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/classement': {
      id: '/eleve/classement'
      path: '/classement'
      fullPath: '/eleve/classement'
      preLoaderRoute: typeof EleveClassementRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/boutique': {
      id: '/eleve/boutique'
      path: '/boutique'
      fullPath: '/eleve/boutique'
      preLoaderRoute: typeof EleveBoutiqueRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/badges': {
      id: '/eleve/badges'
      path: '/badges'
      fullPath: '/eleve/badges'
      preLoaderRoute: typeof EleveBadgesRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/abonnement': {
      id: '/eleve/abonnement'
      path: '/abonnement'
      fullPath: '/eleve/abonnement'
      preLoaderRoute: typeof EleveAbonnementRouteImport
      parentRoute: typeof EleveRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ressources': {
      id: '/admin/ressources'
      path: '/ressources'
      fullPath: '/admin/ressources'
      preLoaderRoute: typeof AdminRessourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matieres': {
      id: '/admin/matieres'
      path: '/matieres'
      fullPath: '/admin/matieres'
      preLoaderRoute: typeof AdminMatieresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketplace': {
      id: '/admin/marketplace'
      path: '/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abonnements': {
      id: '/admin/abonnements'
      path: '/abonnements'
      fullPath: '/admin/abonnements'
      preLoaderRoute: typeof AdminAbonnementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/prof/ressources/': {
      id: '/prof/ressources/'
      path: '/ressources'
      fullPath: '/prof/ressources/'
      preLoaderRoute: typeof ProfRessourcesIndexRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/produits/': {
      id: '/prof/produits/'
      path: '/produits'
      fullPath: '/prof/produits/'
      preLoaderRoute: typeof ProfProduitsIndexRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/groupes/': {
      id: '/prof/groupes/'
      path: '/groupes'
      fullPath: '/prof/groupes/'
      preLoaderRoute: typeof ProfGroupesIndexRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/exercices/': {
      id: '/prof/exercices/'
      path: '/exercices'
      fullPath: '/prof/exercices/'
      preLoaderRoute: typeof ProfExercicesIndexRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/eleves/': {
      id: '/prof/eleves/'
      path: '/eleves'
      fullPath: '/prof/eleves/'
      preLoaderRoute: typeof ProfElevesIndexRouteImport
      parentRoute: typeof ProfRoute
    }
    '/eleve/examens/': {
      id: '/eleve/examens/'
      path: '/examens'
      fullPath: '/eleve/examens/'
      preLoaderRoute: typeof EleveExamensIndexRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/devoirs/': {
      id: '/eleve/devoirs/'
      path: '/devoirs'
      fullPath: '/eleve/devoirs/'
      preLoaderRoute: typeof EleveDevoirsIndexRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/bibliotheque/': {
      id: '/eleve/bibliotheque/'
      path: '/bibliotheque'
      fullPath: '/eleve/bibliotheque/'
      preLoaderRoute: typeof EleveBibliothequeIndexRouteImport
      parentRoute: typeof EleveRoute
    }
    '/admin/utilisateurs/': {
      id: '/admin/utilisateurs/'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs/'
      preLoaderRoute: typeof AdminUtilisateursIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions/': {
      id: '/admin/questions/'
      path: '/questions'
      fullPath: '/admin/questions/'
      preLoaderRoute: typeof AdminQuestionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gestionnaires/': {
      id: '/admin/gestionnaires/'
      path: '/gestionnaires'
      fullPath: '/admin/gestionnaires/'
      preLoaderRoute: typeof AdminGestionnairesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/examens/': {
      id: '/admin/examens/'
      path: '/examens'
      fullPath: '/admin/examens/'
      preLoaderRoute: typeof AdminExamensIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/prof/ressources/$id': {
      id: '/prof/ressources/$id'
      path: '/ressources/$id'
      fullPath: '/prof/ressources/$id'
      preLoaderRoute: typeof ProfRessourcesIdRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/produits/$id': {
      id: '/prof/produits/$id'
      path: '/produits/$id'
      fullPath: '/prof/produits/$id'
      preLoaderRoute: typeof ProfProduitsIdRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/groupes/$id': {
      id: '/prof/groupes/$id'
      path: '/groupes/$id'
      fullPath: '/prof/groupes/$id'
      preLoaderRoute: typeof ProfGroupesIdRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/exercices/nouveau': {
      id: '/prof/exercices/nouveau'
      path: '/exercices/nouveau'
      fullPath: '/prof/exercices/nouveau'
      preLoaderRoute: typeof ProfExercicesNouveauRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/exercices/$id': {
      id: '/prof/exercices/$id'
      path: '/exercices/$id'
      fullPath: '/prof/exercices/$id'
      preLoaderRoute: typeof ProfExercicesIdRouteImport
      parentRoute: typeof ProfRoute
    }
    '/prof/eleves/$id': {
      id: '/prof/eleves/$id'
      path: '/eleves/$id'
      fullPath: '/prof/eleves/$id'
      preLoaderRoute: typeof ProfElevesIdRouteImport
      parentRoute: typeof ProfRoute
    }
    '/eleve/salle/$id': {
      id: '/eleve/salle/$id'
      path: '/salle/$id'
      fullPath: '/eleve/salle/$id'
      preLoaderRoute: typeof EleveSalleIdRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/examens/$id': {
      id: '/eleve/examens/$id'
      path: '/examens/$id'
      fullPath: '/eleve/examens/$id'
      preLoaderRoute: typeof EleveExamensIdRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/devoirs/$id': {
      id: '/eleve/devoirs/$id'
      path: '/devoirs/$id'
      fullPath: '/eleve/devoirs/$id'
      preLoaderRoute: typeof EleveDevoirsIdRouteImport
      parentRoute: typeof EleveRoute
    }
    '/eleve/bibliotheque/$id': {
      id: '/eleve/bibliotheque/$id'
      path: '/bibliotheque/$id'
      fullPath: '/eleve/bibliotheque/$id'
      preLoaderRoute: typeof EleveBibliothequeIdRouteImport
      parentRoute: typeof EleveRoute
    }
    '/admin/utilisateurs/$id': {
      id: '/admin/utilisateurs/$id'
      path: '/utilisateurs/$id'
      fullPath: '/admin/utilisateurs/$id'
      preLoaderRoute: typeof AdminUtilisateursIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions/nouveau': {
      id: '/admin/questions/nouveau'
      path: '/questions/nouveau'
      fullPath: '/admin/questions/nouveau'
      preLoaderRoute: typeof AdminQuestionsNouveauRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions/$questionId': {
      id: '/admin/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/admin/questions/$questionId'
      preLoaderRoute: typeof AdminQuestionsQuestionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groupes/$id': {
      id: '/admin/groupes/$id'
      path: '/groupes/$id'
      fullPath: '/admin/groupes/$id'
      preLoaderRoute: typeof AdminGroupesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gestionnaires/$id': {
      id: '/admin/gestionnaires/$id'
      path: '/gestionnaires/$id'
      fullPath: '/admin/gestionnaires/$id'
      preLoaderRoute: typeof AdminGestionnairesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/examens/$examId': {
      id: '/admin/examens/$examId'
      path: '/examens/$examId'
      fullPath: '/admin/examens/$examId'
      preLoaderRoute: typeof AdminExamensExamIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devoirs/$id': {
      id: '/admin/devoirs/$id'
      path: '/devoirs/$id'
      fullPath: '/admin/devoirs/$id'
      preLoaderRoute: typeof AdminDevoirsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAbonnementsRoute: typeof AdminAbonnementsRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminMarketplaceRoute: typeof AdminMarketplaceRoute
  AdminMatieresRoute: typeof AdminMatieresRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminRessourcesRoute: typeof AdminRessourcesRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDevoirsIdRoute: typeof AdminDevoirsIdRoute
  AdminExamensExamIdRoute: typeof AdminExamensExamIdRoute
  AdminGestionnairesIdRoute: typeof AdminGestionnairesIdRoute
  AdminGroupesIdRoute: typeof AdminGroupesIdRoute
  AdminQuestionsQuestionIdRoute: typeof AdminQuestionsQuestionIdRoute
  AdminQuestionsNouveauRoute: typeof AdminQuestionsNouveauRoute
  AdminUtilisateursIdRoute: typeof AdminUtilisateursIdRoute
  AdminExamensIndexRoute: typeof AdminExamensIndexRoute
  AdminGestionnairesIndexRoute: typeof AdminGestionnairesIndexRoute
  AdminQuestionsIndexRoute: typeof AdminQuestionsIndexRoute
  AdminUtilisateursIndexRoute: typeof AdminUtilisateursIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbonnementsRoute: AdminAbonnementsRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminMarketplaceRoute: AdminMarketplaceRoute,
  AdminMatieresRoute: AdminMatieresRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminRessourcesRoute: AdminRessourcesRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDevoirsIdRoute: AdminDevoirsIdRoute,
  AdminExamensExamIdRoute: AdminExamensExamIdRoute,
  AdminGestionnairesIdRoute: AdminGestionnairesIdRoute,
  AdminGroupesIdRoute: AdminGroupesIdRoute,
  AdminQuestionsQuestionIdRoute: AdminQuestionsQuestionIdRoute,
  AdminQuestionsNouveauRoute: AdminQuestionsNouveauRoute,
  AdminUtilisateursIdRoute: AdminUtilisateursIdRoute,
  AdminExamensIndexRoute: AdminExamensIndexRoute,
  AdminGestionnairesIndexRoute: AdminGestionnairesIndexRoute,
  AdminQuestionsIndexRoute: AdminQuestionsIndexRoute,
  AdminUtilisateursIndexRoute: AdminUtilisateursIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EleveRouteChildren {
  EleveAbonnementRoute: typeof EleveAbonnementRoute
  EleveBadgesRoute: typeof EleveBadgesRoute
  EleveBoutiqueRoute: typeof EleveBoutiqueRoute
  EleveClassementRoute: typeof EleveClassementRoute
  EleveCoachRoute: typeof EleveCoachRoute
  EleveDashboardRoute: typeof EleveDashboardRoute
  EleveHistoriqueRoute: typeof EleveHistoriqueRoute
  EleveJeuRoute: typeof EleveJeuRoute
  EleveLiveRoute: typeof EleveLiveRoute
  EleveMessagesRoute: typeof EleveMessagesRoute
  EleveMonAbonnementRoute: typeof EleveMonAbonnementRoute
  EleveNotificationsRoute: typeof EleveNotificationsRoute
  ElevePreferencesRoute: typeof ElevePreferencesRoute
  EleveProfilRoute: typeof EleveProfilRoute
  EleveIndexRoute: typeof EleveIndexRoute
  EleveBibliothequeIdRoute: typeof EleveBibliothequeIdRoute
  EleveDevoirsIdRoute: typeof EleveDevoirsIdRoute
  EleveExamensIdRoute: typeof EleveExamensIdRoute
  EleveSalleIdRoute: typeof EleveSalleIdRoute
  EleveBibliothequeIndexRoute: typeof EleveBibliothequeIndexRoute
  EleveDevoirsIndexRoute: typeof EleveDevoirsIndexRoute
  EleveExamensIndexRoute: typeof EleveExamensIndexRoute
}

const EleveRouteChildren: EleveRouteChildren = {
  EleveAbonnementRoute: EleveAbonnementRoute,
  EleveBadgesRoute: EleveBadgesRoute,
  EleveBoutiqueRoute: EleveBoutiqueRoute,
  EleveClassementRoute: EleveClassementRoute,
  EleveCoachRoute: EleveCoachRoute,
  EleveDashboardRoute: EleveDashboardRoute,
  EleveHistoriqueRoute: EleveHistoriqueRoute,
  EleveJeuRoute: EleveJeuRoute,
  EleveLiveRoute: EleveLiveRoute,
  EleveMessagesRoute: EleveMessagesRoute,
  EleveMonAbonnementRoute: EleveMonAbonnementRoute,
  EleveNotificationsRoute: EleveNotificationsRoute,
  ElevePreferencesRoute: ElevePreferencesRoute,
  EleveProfilRoute: EleveProfilRoute,
  EleveIndexRoute: EleveIndexRoute,
  EleveBibliothequeIdRoute: EleveBibliothequeIdRoute,
  EleveDevoirsIdRoute: EleveDevoirsIdRoute,
  EleveExamensIdRoute: EleveExamensIdRoute,
  EleveSalleIdRoute: EleveSalleIdRoute,
  EleveBibliothequeIndexRoute: EleveBibliothequeIndexRoute,
  EleveDevoirsIndexRoute: EleveDevoirsIndexRoute,
  EleveExamensIndexRoute: EleveExamensIndexRoute,
}

const EleveRouteWithChildren = EleveRoute._addFileChildren(EleveRouteChildren)

interface ParentRouteChildren {
  ParentBoutiqueRoute: typeof ParentBoutiqueRoute
  ParentDevoirsRoute: typeof ParentDevoirsRoute
  ParentNotificationsRoute: typeof ParentNotificationsRoute
  ParentPreferencesRoute: typeof ParentPreferencesRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentBoutiqueRoute: ParentBoutiqueRoute,
  ParentDevoirsRoute: ParentDevoirsRoute,
  ParentNotificationsRoute: ParentNotificationsRoute,
  ParentPreferencesRoute: ParentPreferencesRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface ProfRouteChildren {
  ProfMessagesRoute: typeof ProfMessagesRoute
  ProfNotificationsRoute: typeof ProfNotificationsRoute
  ProfPlanningRoute: typeof ProfPlanningRoute
  ProfPreferencesRoute: typeof ProfPreferencesRoute
  ProfRapportsRoute: typeof ProfRapportsRoute
  ProfIndexRoute: typeof ProfIndexRoute
  ProfElevesIdRoute: typeof ProfElevesIdRoute
  ProfExercicesIdRoute: typeof ProfExercicesIdRoute
  ProfExercicesNouveauRoute: typeof ProfExercicesNouveauRoute
  ProfGroupesIdRoute: typeof ProfGroupesIdRoute
  ProfProduitsIdRoute: typeof ProfProduitsIdRoute
  ProfRessourcesIdRoute: typeof ProfRessourcesIdRoute
  ProfElevesIndexRoute: typeof ProfElevesIndexRoute
  ProfExercicesIndexRoute: typeof ProfExercicesIndexRoute
  ProfGroupesIndexRoute: typeof ProfGroupesIndexRoute
  ProfProduitsIndexRoute: typeof ProfProduitsIndexRoute
  ProfRessourcesIndexRoute: typeof ProfRessourcesIndexRoute
}

const ProfRouteChildren: ProfRouteChildren = {
  ProfMessagesRoute: ProfMessagesRoute,
  ProfNotificationsRoute: ProfNotificationsRoute,
  ProfPlanningRoute: ProfPlanningRoute,
  ProfPreferencesRoute: ProfPreferencesRoute,
  ProfRapportsRoute: ProfRapportsRoute,
  ProfIndexRoute: ProfIndexRoute,
  ProfElevesIdRoute: ProfElevesIdRoute,
  ProfExercicesIdRoute: ProfExercicesIdRoute,
  ProfExercicesNouveauRoute: ProfExercicesNouveauRoute,
  ProfGroupesIdRoute: ProfGroupesIdRoute,
  ProfProduitsIdRoute: ProfProduitsIdRoute,
  ProfRessourcesIdRoute: ProfRessourcesIdRoute,
  ProfElevesIndexRoute: ProfElevesIndexRoute,
  ProfExercicesIndexRoute: ProfExercicesIndexRoute,
  ProfGroupesIndexRoute: ProfGroupesIndexRoute,
  ProfProduitsIndexRoute: ProfProduitsIndexRoute,
  ProfRessourcesIndexRoute: ProfRessourcesIndexRoute,
}

const ProfRouteWithChildren = ProfRoute._addFileChildren(ProfRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionParentRoute: ConnexionParentRoute,
  EleveRoute: EleveRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ParentRoute: ParentRouteWithChildren,
  ProfRoute: ProfRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
